/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dl_jni_JniTest */

#ifndef _Included_com_dl_jni_JniTest
#define _Included_com_dl_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dl_jni_JniTest
 * Method:    hello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dl_jni_JniTest_hello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
