---
spring:
  profiles: discovery
server:
  port: 8761
eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
           
---
spring:
  profiles: user
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
server:
  port: 8000
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
    
---
spring:
  profiles: movie    
  application:
    name: microservice-consumer-movie-ribbon
server:
  port: 8010
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    hostname: localhost
    
---
spring:
  profiles: hystrix    
  application:
    name: hystrix-dashboard
server:
  port: 8030
security.basic.enabled: false
turbine:
  aggregator:
    clusterConfig: default
    appConfig: microservice-consumer-movie-ribbon
    clusterNameExpression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

---
spring:
  profiles: gateway    
  application:
    name: microservice-api-gateway
server:
  port: 8050
eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
zuul:
  ignored-services: microservice-provider-user
  routes:
    movie: 
      path: /movie/** 
      service-id: microservice-consumer-movie-ribbon
      
---
spring:
  profiles: config   
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eacdy/spring-cloud-study/
          search-paths: config-repo
          username:
          password:
server:
  port: 8040
  
